"use strict";

// This UI is only a client of the existing API; it never writes data directly.
const el = (id) => document.getElementById(id);
const lastKey = "urpp-local-learning-v01:last-session";
let active = null;
let messageCount = 0;
let busy = false;

function setStatus(value) { el("status").textContent = value; }
function updateButtons() {
  el("send").disabled = busy || active === null;
  el("refresh").disabled = busy || active === null;
  el("upload").disabled = busy;
  el("resume").disabled = busy;
  el("inspect").disabled = busy || active === null;
}
async function api(path, payload) {
  const config = {
    cache: "no-store", credentials: "omit", redirect: "error",
    headers: { "X-URPP-Local-Request": "1" }
  };
  if (payload !== undefined) {
    config.method = "POST";
    config.headers["Content-Type"] = "application/json";
    config.body = JSON.stringify(payload);
  }
  const response = await fetch(path, config);
  const data = await response.json();
  if (!response.ok) throw new Error(typeof data.detail === "string" ? data.detail : "Request failed.");
  return data;
}
function render(snapshot) {
  messageCount = snapshot.message_count;
  const log = el("history");
  log.replaceChildren();
  if (!snapshot.messages.length) {
    const empty = document.createElement("p");
    empty.className = "hint";
    empty.textContent = "Session created. You can start asking questions.";
    log.append(empty);
  }
  for (const entry of snapshot.messages) {
    const box = document.createElement("div");
    box.className = "message " + (entry.role === "student" ? "student" : "professor");
    const label = document.createElement("strong");
    const names = {
      course_grounded: "From material",
      insufficient_evidence: "Not enough material",
      general_knowledge: "General knowledge",
      legacy_unclassified: "Old record · source unclassified"
    };
    label.textContent = entry.role === "student" ? "You" :
      "Professor · " + (names[entry.answer_status] || "Source unclassified");
    const body = document.createElement("div");
    // Untrusted model text is converted to safe DOM nodes, never parsed as HTML.
    if (entry.role === "professor" && entry.answer_status !== "insufficient_evidence") {
      window.URPPMarkdownV01.renderInto(body, entry.text);
    } else {
      body.textContent = entry.text;
    }
    box.append(label, body);
    log.append(box);
  }
  log.scrollTop = log.scrollHeight;
  el("session").textContent = "Session ID: " + snapshot.session_id +
    "\nSaved turns: " + snapshot.turn_count +
    "\nPack SHA-256: " + snapshot.pack_sha256;
  renderGenerated(snapshot.messages);
}
function node(tag, value, className) {
  const item = document.createElement(tag);
  if (className) item.className = className;
  item.textContent = value;
  return item;
}
function renderGenerated(messages) {
  const output = el("generated-view");
  output.replaceChildren();
  const generated = messages.filter((message) => message.role === "professor");
  if (!generated.length) {
    output.append(node("p", "This Session has no model answers yet.", "hint"));
    return;
  }
  generated.forEach((message, index) => {
    const item = node("article", "", "model-output");
    const label = message.answer_status === "insufficient_evidence" ?
      "System notice: not enough material" : message.answer_status === "legacy_unclassified" ?
      "Old reply · source unclassified" : "Model answer · " +
      (message.answer_status || "Source unclassified");
    item.append(node("strong", "Reply " + (index + 1) + " · " + label));
    const detail = node("div", "");
    if (message.answer_status === "insufficient_evidence") {
      detail.textContent = message.text;
    } else {
      window.URPPMarkdownV01.renderInto(detail, message.text);
    }
    item.append(detail);
    output.append(item);
  });
}
function renderCoursePack(pack) {
  const view = el("pack-view");
  view.replaceChildren();
  const flow = node("div", "", "pack-flow");
  const steps = [
    ["1 · Save original", "Uploaded file identified by SHA-256"],
    ["2 · Extract text", pack.sources.length + " excerpts with source locations"],
    ["3 · Build Course Pack", "Objective + excerpt references; version pinned"],
    ["4 · Professor chat", "Answers below, saved after generation"]
  ];
  for (const [title, description] of steps) {
    const item = node("div", "", "pack-step");
    item.append(node("strong", title), node("span", description));
    flow.append(item);
  }
  view.append(flow);
  const info = node("dl", "", "pack-meta");
  for (const [label, value] of [
    ["Course Pack", pack.pack_id], ["Pack SHA-256", pack.pack_sha256],
    ["Objective source", "Entered by you at upload"], ["Learning objective", pack.objective.description],
    ["Course path", "Not generated by the model yet; there is only one learning objective"]
  ]) {
    info.append(node("dt", label), node("dd", value));
  }
  view.append(info, node("h3", "Original-text excerpts in the Course Pack (click to expand)"));
  for (const [index, source] of pack.sources.entries()) {
    const detail = node("details", "", "excerpt");
    const where = source.pages ? " · page " + source.pages : "";
    detail.append(node("summary", "Excerpt " + (index + 1) + " · " + source.filename + where));
    detail.append(node("p", "Source ID: " + source.source_id +
      " · original text SHA-256: " + source.content_sha256, "hint"));
    detail.append(node("pre", source.excerpt_text));
    view.append(detail);
  }
}
async function loadCoursePack() {
  if (!active) throw new Error("No active Session.");
  const query = new URLSearchParams({ pack_sha256: active.pack_sha256 });
  const pack = await api("/api/session/" + encodeURIComponent(active.session_id) +
    "/course-pack?" + query);
  renderCoursePack(pack);
}
function remember(snapshot) {
  active = { session_id: snapshot.session_id, pack_sha256: snapshot.pack_sha256 };
  // A Session ID is sensitive local state; do not sync or share this browser profile.
  localStorage.setItem(lastKey, JSON.stringify(active));
  render(snapshot);
  updateButtons();
}
async function refresh() {
  if (!active) throw new Error("No active Session.");
  const query = new URLSearchParams({ pack_sha256: active.pack_sha256 });
  const snapshot = await api("/api/session/" + encodeURIComponent(active.session_id) + "?" + query);
  render(snapshot);
  return snapshot;
}
function fileBase64(file) {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.onerror = () => reject(new Error("Could not read the selected file."));
    reader.onload = () => resolve(String(reader.result).split(",", 2)[1]);
    reader.readAsDataURL(file);
  });
}
async function run(fn) {
  if (busy) return;
  busy = true;
  updateButtons();
  try { await fn(); }
  catch (error) { setStatus(error instanceof Error ? error.message : "Operation failed."); }
  finally { busy = false; updateButtons(); }
}
el("upload").addEventListener("click", () => run(async () => {
  const file = el("material").files[0];
  if (!file) throw new Error("Please choose a material file.");
  if (!el("permission").checked) throw new Error("Please confirm you have the right to use this material locally first.");
  const ext = file.name.toLowerCase().split(".").pop();
  const limit = ext === "pdf" ? 8 * 1024 * 1024 : 128 * 1024;
  if (!["txt", "md", "markdown", "pdf"].includes(ext) || file.size === 0 || file.size > limit) {
    throw new Error("File type or size is not supported.");
  }
  setStatus("Importing material…");
  const snapshot = await api("/api/upload", {
    filename: file.name, file_base64: await fileBase64(file),
    objective_description: el("objective").value.trim(), allow_local_teaching: true
  });
  remember(snapshot);
  await loadCoursePack();
  setStatus("Material imported. Session saved locally.");
}));
el("resume").addEventListener("click", () => run(async () => {
  const saved = JSON.parse(localStorage.getItem(lastKey) || "null");
  if (!saved || typeof saved.session_id !== "string" || typeof saved.pack_sha256 !== "string") {
    throw new Error("No recent Session to resume in this browser.");
  }
  active = saved;
  await refresh();
  await loadCoursePack();
  setStatus("Conversation restored from SQLite.");
}));
el("refresh").addEventListener("click", () => run(async () => {
  await refresh();
  await loadCoursePack();
  setStatus("Conversation history reloaded.");
}));
el("inspect").addEventListener("click", () => run(async () => {
  await loadCoursePack();
  setStatus("Saved Course Pack reloaded.");
}));
el("send").addEventListener("click", () => run(async () => {
  if (!active) throw new Error("Import material or resume a Session first.");
  const question = el("question").value.trim();
  if (!question || question.length > 1500) throw new Error("Questions must be 1–1500 characters.");
  setStatus("Local Professor is generating an answer…");
  try {
    const snapshot = await api("/api/chat", {
      ...active, student_text: question, expected_message_count: messageCount,
      mode: el("answer-mode").value
    });
    render(snapshot);
    el("question").value = "";
    setStatus("This exchange has been saved.");
  } catch (error) {
    // The server might have committed a turn before a connection error.
    try { await refresh(); } catch { /* Keep the original error. */ }
    throw error;
  }
}));
if (localStorage.getItem(lastKey)) {
  setStatus("Found a recent Session; click the button on the left to resume it.");
}
