"""
URPP Design 01D — Persisted Numeric Teaching Loop tests.

All Agent responses and student data are synthetic.
SQLite is isolated for each test.

These tests validate internal integration, not authentication
or production PostgreSQL concurrency behavior.
"""

from datetime import datetime, timedelta, timezone

import pytest

from sqlalchemy import create_engine, event
from sqlalchemy.orm import sessionmaker

from app.repositories.assessment_records_v02 import (
    AssessmentRecordRepositoryV02,
    Base,
)

from app.repositories.numeric_assignment_v01 import (
    NumericAssignmentRepositoryV01,
)

from app.services.assessment.models_v02 import (
    AssessmentItemV02,
    NumericRubricV02,
)

from app.services.decision.engine_v01 import (
    DecisionEngineV01,
    RuleBasedControllerV01,
)

from app.services.decision.persisted_numeric_session_loop_v01 import (
    PersistedNumericTeachingLoopV01,
)

from app.services.decision.turn_orchestrator_v01 import (
    TeachingTurnOrchestratorV01,
)


NOW = datetime(2026, 9, 19, tzinfo=timezone.utc)


class StubAgent:
    """
    Test-only Agent port.

    Structured delivery uses the stored assessment prompt,
    not the content generated by this stub.
    """

    def __init__(self, content: str):
        self.content = content
        self.calls = 0

    def produce(self, *, context, decision):
        self.calls += 1
        return self.content


@pytest.fixture
def environment():
    engine = create_engine(
        "sqlite+pysqlite:///:memory:"
    )

    @event.listens_for(engine, "connect")
    def enable_foreign_keys(connection, _record):
        cursor = connection.cursor()
        cursor.execute("PRAGMA foreign_keys=ON")
        cursor.close()

    Base.metadata.create_all(engine)

    session_factory = sessionmaker(
        bind=engine,
        expire_on_commit=False,
    )

    assessments = AssessmentRecordRepositoryV02(
        session_factory
    )

    current_time = [
        NOW + timedelta(seconds=2)
    ]

    assignments = NumericAssignmentRepositoryV01(
        assessments,
        clock=lambda: current_time[0],
    )

    professor = StubAgent("Conceptual explanation.")

    assessment_agent = StubAgent(
        "An Agent-generated assessment placeholder."
    )

    orchestrator = TeachingTurnOrchestratorV01(
        decision_engine=DecisionEngineV01(
            RuleBasedControllerV01()
        ),
        professor_agent=professor,
        assessment_agent=assessment_agent,
    )

    loop = PersistedNumericTeachingLoopV01(
        assessment_repository=assessments,
        assignment_repository=assignments,
        turn_orchestrator=orchestrator,
        student_id="student-001",
        course_id="course-001",
        objective_id="objective-001",
        session_id="session-001",
        as_of=NOW,
    )

    yield (
        assessments,
        assignments,
        loop,
        current_time,
        assessment_agent,
    )

    engine.dispose()


def make_item(
    *,
    item_id="item-001",
    expected=5.0,
    prompt="What is 2 + 3?",
):
    return AssessmentItemV02(
        assessment_item_id=item_id,
        course_id="course-001",
        objective_id="objective-001",
        prompt=prompt,
        rubric=NumericRubricV02(
            expected_value=expected,
            absolute_tolerance=0.0,
            rubric_version="numeric-rubric-v1",
        ),
        alignment_verified=True,
    )


def deliver(
    loop,
    *,
    item_id="item-001",
    decision_id="decision-001",
    requested_at=NOW,
):
    return loop.deliver_numeric_assessment(
        assessment_item_id=item_id,
        item_revision=1,
        decision_id=decision_id,
        requested_at=requested_at,
    )


def test_delivery_creates_persisted_pending_assignment(
    environment,
):
    assessments, assignments, loop, _, agent = environment

    assessments.save_item(
        make_item(),
        revision=1,
    )

    delivery = deliver(loop)

    stored = assignments.load_assignment(
        delivery.assignment_id
    )

    assert delivery.prompt == "What is 2 + 3?"
    assert stored.status == "pending"
    assert stored.assessment_item_id == "item-001"
    assert stored.item_revision == 1
    assert stored.student_id == "student-001"
    assert stored.session_id == "session-001"

    assert loop.pending_assignment_id == delivery.assignment_id
    assert loop.requires_recovery is False
    assert agent.calls == 1


def test_submission_completes_assignment_and_updates_state(
    environment,
):
    assessments, assignments, loop, _, _ = environment

    assessments.save_item(
        make_item(),
        revision=1,
    )

    delivery = deliver(loop)

    updated = loop.submit_numeric_answer(
        assignment_id=delivery.assignment_id,
        response_text="5",
    )

    stored = assignments.load_assignment(
        delivery.assignment_id
    )

    assert stored.status == "completed"
    assert stored.completed_attempt_id is not None

    attempt, revision = assessments.load_attempt(
        stored.completed_attempt_id
    )

    assert revision == 1
    assert attempt.response_text == "5"
    assert attempt.assistance_level is None
    assert attempt.prior_solution_exposure is None

    # A correct answer with unknown assistance conditions
    # cannot be treated as an independent mastery success.
    assert updated.independent_success_count == 0
    assert updated.state.value == "unknown"

    assert loop.state == updated
    assert loop.pending_assignment_id is None
    assert loop.completed_assignment_ids == (
        delivery.assignment_id,
    )


def test_two_database_backed_turns_run_in_sequence(
    environment,
):
    (
        assessments,
        assignments,
        loop,
        current_time,
        agent,
    ) = environment

    assessments.save_item(
        make_item(),
        revision=1,
    )

    assessments.save_item(
        make_item(
            item_id="item-002",
            expected=7.0,
            prompt="What is 3 + 4?",
        ),
        revision=1,
    )

    first = deliver(loop)

    first_state = loop.submit_numeric_answer(
        assignment_id=first.assignment_id,
        response_text="5",
    )

    assert first_state.independent_success_count == 0

    current_time[0] = NOW + timedelta(seconds=5)

    second = deliver(
        loop,
        item_id="item-002",
        decision_id="decision-002",
        requested_at=NOW + timedelta(seconds=3),
    )

    assert second.assignment_id != first.assignment_id
    assert second.prompt == "What is 3 + 4?"

    second_state = loop.submit_numeric_answer(
        assignment_id=second.assignment_id,
        response_text="7",
    )

    first_record = assignments.load_assignment(
        first.assignment_id
    )

    second_record = assignments.load_assignment(
        second.assignment_id
    )

    assert first_record.status == "completed"
    assert second_record.status == "completed"

    assert (
        first_record.completed_attempt_id
        != second_record.completed_attempt_id
    )

    assert loop.completed_assignment_ids == (
        first.assignment_id,
        second.assignment_id,
    )

    assert loop.state == second_state
    assert loop.pending_assignment_id is None
    assert loop.requires_recovery is False
    assert agent.calls == 2


def test_wrong_assignment_id_does_not_submit(
    environment,
):
    assessments, assignments, loop, _, _ = environment

    assessments.save_item(
        make_item(),
        revision=1,
    )

    delivery = deliver(loop)

    with pytest.raises(
        ValueError,
        match="Assignment ID",
    ):
        loop.submit_numeric_answer(
            assignment_id="different-assignment",
            response_text="5",
        )

    stored = assignments.load_assignment(
        delivery.assignment_id
    )

    assert stored.status == "pending"
    assert stored.completed_attempt_id is None

    assert loop.pending_assignment_id == delivery.assignment_id
    assert loop.requires_recovery is False


def test_invalid_response_preserves_pending_assignment(
    environment,
):
    assessments, assignments, loop, _, _ = environment

    assessments.save_item(
        make_item(),
        revision=1,
    )

    delivery = deliver(loop)

    with pytest.raises(
        ValueError,
        match="response_text",
    ):
        loop.submit_numeric_answer(
            assignment_id=delivery.assignment_id,
            response_text="   ",
        )

    stored = assignments.load_assignment(
        delivery.assignment_id
    )

    assert stored.status == "pending"
    assert loop.pending_assignment_id == delivery.assignment_id

    updated = loop.submit_numeric_answer(
        assignment_id=delivery.assignment_id,
        response_text="5",
    )

    assert updated.state.value == "unknown"
    assert loop.pending_assignment_id is None


def test_second_turn_cannot_start_while_pending(
    environment,
):
    assessments, _, loop, _, _ = environment

    assessments.save_item(
        make_item(),
        revision=1,
    )

    deliver(loop)

    with pytest.raises(
        ValueError,
        match="pending assignment",
    ):
        deliver(
            loop,
            decision_id="decision-002",
        )


def test_submission_requires_prior_delivery(
    environment,
):
    _, _, loop, _, _ = environment

    with pytest.raises(
        ValueError,
        match="No numeric assignment",
    ):
        loop.submit_numeric_answer(
            assignment_id="assignment-001",
            response_text="5",
        )
