"""
URPP Implementation 13E-4D-1.

Non-authoritative post-turn shadow observation.

This module receives an already completed teaching turn.
It never calls the Decision Engine or Teaching Agents.

A shadow failure must not replace the completed turn.
"""

from copy import deepcopy
from dataclasses import dataclass
from typing import Literal

from app.services.decision.observation_aware_shadow_policy_v01 import (
    ObservationAwareShadowReportV01,
    evaluate_observation_shadow_v01,
)
from app.services.decision.personalized_turn_orchestrator_v01 import (
    PersonalizedTeachingTurnResultV01,
)
from app.services.decision.student_request_v01 import (
    PersonalizedDecisionContextV01,
)
from app.services.decision.teaching_observation_context_v01 import (
    TeachingObservationContextV01,
)


POST_TURN_OBSERVER_VERSION = "post-turn-shadow-observer-v0.1"

ShadowObservationStatusV01 = Literal[
    "evaluated",
    "unavailable",
    "failed",
]


@dataclass(frozen=True)
class PostTurnShadowOutcomeV01:
    """
    Preserve the actual teaching result alongside optional
    shadow information.

    completed_turn is the original object, not a replacement
    teaching decision generated by the observer.
    """

    completed_turn: PersonalizedTeachingTurnResultV01

    status: ShadowObservationStatusV01

    report: ObservationAwareShadowReportV01 | None

    failure_code: Literal["shadow_evaluation_failed"] | None

    observer_version: str = POST_TURN_OBSERVER_VERSION

    def __post_init__(self) -> None:
        if self.status == "evaluated":
            if self.report is None or self.failure_code is not None:
                raise ValueError(
                    "Evaluated outcome requires a report "
                    "and no failure code."
                )

        elif self.status == "unavailable":
            if self.report is not None or self.failure_code is not None:
                raise ValueError(
                    "Unavailable outcome cannot contain "
                    "a report or failure code."
                )

        elif self.status == "failed":
            if (
                self.report is not None
                or self.failure_code != "shadow_evaluation_failed"
            ):
                raise ValueError(
                    "Failed outcome requires the controlled "
                    "shadow failure code and no report."
                )

        else:
            raise ValueError(
                "Unsupported shadow observation status."
            )


def observe_completed_turn_v01(
    *,
    decision_context: PersonalizedDecisionContextV01,
    completed_turn: PersonalizedTeachingTurnResultV01,
    observation_context: TeachingObservationContextV01 | None,
) -> PostTurnShadowOutcomeV01:
    """
    Evaluate a completed teaching turn without re-deciding.

    Only optional shadow evaluation is isolated. The original
    Decision Engine and Teaching Agent must run outside this
    function and retain their existing failure behavior.
    """

    if not isinstance(
        decision_context,
        PersonalizedDecisionContextV01,
    ):
        raise TypeError(
            "decision_context must be PersonalizedDecisionContextV01."
        )

    if not isinstance(
        completed_turn,
        PersonalizedTeachingTurnResultV01,
    ):
        raise TypeError(
            "completed_turn must be PersonalizedTeachingTurnResultV01."
        )

    if (
        observation_context is not None
        and not isinstance(
            observation_context,
            TeachingObservationContextV01,
        )
    ):
        raise TypeError(
            "observation_context must be "
            "TeachingObservationContextV01 or None."
        )

    # No observation source: no shadow assessment is attempted.
    # The original completed turn remains available.
    if observation_context is None:
        return PostTurnShadowOutcomeV01(
            completed_turn=completed_turn,
            status="unavailable",
            report=None,
            failure_code=None,
        )

    try:
        # The shadow policy receives separate in-memory copies.
        # The original actual decision and Student State are
        # never passed directly into its evaluation function.

        shadow_decision_context = deepcopy(
            decision_context
        )

        shadow_decision_result = deepcopy(
            completed_turn.decision
        )

        shadow_observation_context = deepcopy(
            observation_context
        )

        before_state = (
            shadow_decision_context
            .decision_context
            .objective_state
            .model_dump(mode="json")
        )

        before_decision = (
            shadow_decision_result.model_dump(mode="json")
        )

        report = evaluate_observation_shadow_v01(
            decision_context=shadow_decision_context,
            decision_result=shadow_decision_result,
            observation_context=shadow_observation_context,
        )

        # Detect unexpected mutations within the shadow copies.
        # Such an evaluation is discarded rather than published.

        after_state = (
            shadow_decision_context
            .decision_context
            .objective_state
            .model_dump(mode="json")
        )

        after_decision = (
            shadow_decision_result.model_dump(mode="json")
        )

        if (
            after_state != before_state
            or after_decision != before_decision
        ):
            raise ValueError(
                "Shadow evaluation modified its input copies."
            )

        if (
            report.decision_id
            != completed_turn.decision.decision.decision_id
            or report.existing_action
            != completed_turn.decision.decision.selected_action
        ):
            raise ValueError(
                "Shadow report does not match the completed turn."
            )

    except Exception:
        # This catch is restricted to post-turn shadow work.
        # It must never enclose run_turn(), Agent execution,
        # assessment delivery or authoritative state updates.
        #
        # Do not expose raw exceptions or student data through
        # the public observation outcome.

        return PostTurnShadowOutcomeV01(
            completed_turn=completed_turn,
            status="failed",
            report=None,
            failure_code="shadow_evaluation_failed",
        )

    return PostTurnShadowOutcomeV01(
        completed_turn=completed_turn,
        status="evaluated",
        report=report,
        failure_code=None,
    )
